### ISSUE TITLE
Mohon dokumentasi petunjuk update

### ISSUE THREAD

**Issue by dbrw** [eraporsmk/eraporsmk#10]
Sekolah kami menginstall erapor pada server linux menggunakan git. Update hingga 5.0.7 dilakukan oleh operator melalui UI, pada update terakhir saya pull lewat git untuk update ke versi 5.0.8. Instalasi kami pada server telah menunjukkan versi terbaru seperti pada screenshot terlampir.

![2020-05-04-103309_520x352_scrot](https://user-images.githubusercontent.com/2887587/80934788-fe39ed80-8df3-11ea-9265-c0c0413d5da4.png)

Yang menjadi masalah adalah pada UI erapor, versi erapor masih menunjukkan 5.0.7, apakah ada command yang perlu dijalankan lagi setelah pull, pindah tag dan migration?

![Screenshot_2020-05-04 e-RaporSMK](https://user-images.githubusercontent.com/2887587/80935273-0bf07280-8df6-11ea-9d4b-ef5a834953a2.png)

Jika memang ada command yang diperlukan untuk melakukan update lewat cli, mohon ditambakan pada seksi update pada dokumentasi.

**Comment by dbrw** [comment]
Update:
Saya ikuti petunjuk di laman https://seputar.erapor-smk.net/2020/04/21/tutorial-update-ke-erapor-smk-5-0-8-di-linux/#more-1140, pada bagian akhir terdapat langkah:

> Anda bisa melanjutkannya sebagai proses update biasa, atau mengeksekusi update melalui http://192.168.0.10/check-update/proses (IP address sesuaikan dengan setting di server Anda). Setelah ini seharusnya aplikasi eRapor SMK Anda sudah menjadi versi 5.0.8

 namun saat link tersebut dikunjungi setelah login, mucul stack trace seperti berikut:

```log
production.ERROR: Use of undefined constant STDIN - assumed 'STDIN' (this will throw an Error in a future version of PHP) {"exception":"[object] (ErrorException(code: 0): Use of undefined constant ST
DIN - assumed 'STDIN' (this will throw an Error in a future version of PHP) at /var/www/erapor5/vendor/symfony/console/Helper/QuestionHelper.php:107)
[stacktrace]
#0 /var/www/erapor5/vendor/symfony/console/Helper/QuestionHelper.php(107): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(2, 'Use of undefine...', '/var/www/erapor...', 107, Array)
#1 /var/www/erapor5/vendor/symfony/console/Helper/QuestionHelper.php(61): Symfony\\Component\\Console\\Helper\\QuestionHelper->doAsk(Object(Illuminate\\Console\\OutputStyle), Object(Symfony\\Component\\Console\\Question\\
ConfirmationQuestion))
#2 /var/www/erapor5/vendor/symfony/console/Style/SymfonyStyle.php(360): Symfony\\Component\\Console\\Helper\\QuestionHelper->ask(Object(Symfony\\Component\\Console\\Input\\StringInput), Object(Illuminate\\Console\\OutputS
tyle), Object(Symfony\\Component\\Console\\Question\\ConfirmationQuestion))
#3 /var/www/erapor5/vendor/symfony/console/Style/SymfonyStyle.php(288): Symfony\\Component\\Console\\Style\\SymfonyStyle->askQuestion(Object(Symfony\\Component\\Console\\Question\\ConfirmationQuestion))
#4 /var/www/erapor5/vendor/laravel/framework/src/Illuminate/Console/Command.php(332): Symfony\\Component\\Console\\Style\\SymfonyStyle->confirm('Do you really w...', false)
#5 /var/www/erapor5/vendor/laravel/framework/src/Illuminate/Console/ConfirmableTrait.php(31): Illuminate\\Console\\Command->confirm('Do you really w...')
#6 /var/www/erapor5/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php(59): Illuminate\\Database\\Console\\Migrations\\MigrateCommand->confirmToProceed()
#7 [internal function]: Illuminate\\Database\\Console\\Migrations\\MigrateCommand->handle()
#8 /var/www/erapor5/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(32): call_user_func_array(Array, Array)
#9 /var/www/erapor5/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(90): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#10 /var/www/erapor5/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(34): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Gecche\\Multidomain\\Foundation\\Application), Array, Object(Closure))
#11 /var/www/erapor5/vendor/laravel/framework/src/Illuminate/Container/Container.php(576): Illuminate\\Container\\BoundMethod::call(Object(Gecche\\Multidomain\\Foundation\\Application), Array, Array, NULL)
#12 /var/www/erapor5/vendor/laravel/framework/src/Illuminate/Console/Command.php(183): Illuminate\\Container\\Container->call(Array)
#13 /var/www/erapor5/vendor/symfony/console/Command/Command.php(255): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\StringInput), Object(Illuminate\\Console\\OutputStyle))
#14 /var/www/erapor5/vendor/laravel/framework/src/Illuminate/Console/Command.php(170): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\StringInput), Object(Illuminate\\Console
\\OutputStyle))
#15 /var/www/erapor5/vendor/symfony/console/Application.php(1001): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\StringInput), Object(Symfony\\Component\\Console\\Output\\BufferedOutput))
#16 /var/www/erapor5/vendor/symfony/console/Application.php(271): Symfony\\Component\\Console\\Application->doRunCommand(Object(Illuminate\\Database\\Console\\Migrations\\MigrateCommand), Object(Symfony\\Component\\Consol
e\\Input\\StringInput), Object(Symfony\\Component\\Console\\Output\\BufferedOutput))
#17 /var/www/erapor5/vendor/symfony/console/Application.php(147): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\StringInput), Object(Symfony\\Component\\Console\\Output\\Buffer
edOutput))
#18 /var/www/erapor5/vendor/laravel/framework/src/Illuminate/Console/Application.php(90): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\StringInput), Object(Symfony\\Component\\C
onsole\\Output\\BufferedOutput))
#19 /var/www/erapor5/vendor/laravel/framework/src/Illuminate/Console/Application.php(182): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\StringInput), Object(Symfony\\Component\\Console\
\Output\\BufferedOutput))
#20 /var/www/erapor5/vendor/gecche/laravel-multidomain/src/Foundation/Console/Kernel.php(73): Illuminate\\Console\\Application->call('migrate', Array, NULL)
#21 /var/www/erapor5/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(239): Gecche\\Multidomain\\Foundation\\Console\\Kernel->call('migrate')
#22 /var/www/erapor5/app/Http/Controllers/UpdateController.php(64): Illuminate\\Support\\Facades\\Facade::__callStatic('call', Array)
#23 [internal function]: App\\Http\\Controllers\\UpdateController->update_versi()
#24 /var/www/erapor5/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array(Array, Array)
#25 /var/www/erapor5/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction('update_versi', Array)
#26 /var/www/erapor5/vendor/laravel/framework/src/Illuminate/Routing/Route.php(219): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(App\\Http\\Controllers\\UpdateController)
, 'update_versi')
#27 /var/www/erapor5/vendor/laravel/framework/src/Illuminate/Routing/Route.php(176): Illuminate\\Routing\\Route->runController()
#28 /var/www/erapor5/vendor/laravel/framework/src/Illuminate/Routing/Router.php(680): Illuminate\\Routing\\Route->run()
#29 /var/www/erapor5/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#30 /var/www/erapor5/vendor/santigarcor/laratrust/src/Middleware/LaratrustRole.php(32): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#31 /var/www/erapor5/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Laratrust\\Middleware\\LaratrustRole->handle(Object(Illuminate\\Http\\Request), Object(Closure), 'admin')
#32 /var/www/erapor5/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#33 /var/www/erapor5/app/Http/Middleware/GetMenu.php(549): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#34 /var/www/erapor5/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): App\\Http\\Middleware\\GetMenu->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#35 /var/www/erapor5/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#36 /var/www/erapor5/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#37 /var/www/erapor5/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#38 /var/www/erapor5/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#39 /var/www/erapor5/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php(43): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#40 /var/www/erapor5/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Auth\\Middleware\\Authenticate->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#41 /var/www/erapor5/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#42 /var/www/erapor5/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(75): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#43 /var/www/erapor5/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#44 /var/www/erapor5/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#45 /var/www/erapor5/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#46 /var/www/erapor5/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#47 /var/www/erapor5/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#48 /var/www/erapor5/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(56): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#49 /var/www/erapor5/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#50 /var/www/erapor5/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#51 /var/www/erapor5/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#52 /var/www/erapor5/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#53 /var/www/erapor5/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#54 /var/www/erapor5/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(66): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#55 /var/www/erapor5/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#56 /var/www/erapor5/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#57 /var/www/erapor5/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#58 /var/www/erapor5/vendor/laravel/framework/src/Illuminate/Routing/Router.php(682): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#59 /var/www/erapor5/vendor/laravel/framework/src/Illuminate/Routing/Router.php(657): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#60 /var/www/erapor5/vendor/laravel/framework/src/Illuminate/Routing/Router.php(623): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#61 /var/www/erapor5/vendor/laravel/framework/src/Illuminate/Routing/Router.php(612): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#62 /var/www/erapor5/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#63 /var/www/erapor5/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#64 /var/www/erapor5/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#65 /var/www/erapor5/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#66 /var/www/erapor5/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#67 /var/www/erapor5/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#68 /var/www/erapor5/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#69 /var/www/erapor5/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#70 /var/www/erapor5/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#71 /var/www/erapor5/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#72 /var/www/erapor5/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#73 /var/www/erapor5/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#74 /var/www/erapor5/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#75 /var/www/erapor5/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#76 /var/www/erapor5/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(62): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#77 /var/www/erapor5/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#78 /var/www/erapor5/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#79 /var/www/erapor5/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#80 /var/www/erapor5/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#81 /var/www/erapor5/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#82 /var/www/erapor5/public/index.php(55): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#83 {main}

```

Error terjadi saat memanggil baris https://github.com/eraporsmk/eraporsmk/blob/master/app/Http/Controllers/UpdateController.php#L64

**Comment by eraporsmk** [comment]
Mohon maaf, php yang dipakai bapak versi berapa?

**Comment by dbrw** [comment]
versi yang kami pakai 7.2, Pak.
```
PHP 7.2.23-1+0~20191008.27+debian9~1.gbp021266 (cli) (built: Oct  8 2019 05:48:16) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with the ionCube PHP Loader + ionCube24 v10.3.9, Copyright (c) 2002-2019, by ionCube Ltd.
    with Zend OPcache v7.2.23-1+0~20191008.27+debian9~1.gbp021266, Copyright (c) 1999-2018, by Zend Technologies
```

**Comment by eraporsmk** [comment]
Silahkan jalankan di ssh/cmd command berikut:
- php artisan git pull origin review
- php artisan config:cache
- php artisan view:clear
- php artisan erapor:update

**Comment by dbrw** [comment]
Terima kasih atas petunjuk yang diberikan.
